cgixx: HttpHeader Class Reference
HttpHeader Class Reference
#include <httpheader.h>
Public Member Functions
HttpHeader ()
void addHeader (const string &)
void addHeader (const string &, const string &)
void commit ()
bool isCommited () const
Private Attributes
bool commited
StringList headersList
Detailed Description
HTTP Header Container all headers are contained in HttpHeader::commited member variable and latter sent to the browser by invoking HttpHeader::commit() member function
Author:
Neel Basu <neel>
Constructor & Destructor Documentation
HttpHeader::HttpHeader ()
Construct's the Class initializes HttpHeader::commited to false
References commited.
Member Function Documentation
void HttpHeader::addHeader (const string & keyVal)
Add's a Header while the header argument is passed as "key: value" format
References headersList.
Referenced by Request::setCookie(), and CGIApp::start().
void HttpHeader::addHeader (const string & key, const string & val)
Add's a header while the header argument is passed as key, value format e.g. with two arguments they are concated with a ':' character and stored into headers Vector
References headersList.
void HttpHeader::commit ()
Commit's HTTP Headers as headers are ultimately stored as "Key: Value" strign in the vector. it just implodes it by a \n and prints it to cout
References commited, and headersList.
Referenced by CGIApp::exec().
bool HttpHeader::isCommited () const
returns boolean value wheather the HTTP headers have been sent or not.
References commited.
Referenced by CGIApp::exec().
Member Data Documentation
bool HttpHeader::commited [private]
Holds boolean value wheather the HTTP headers have been sent or not.
Referenced by commit(), HttpHeader(), and isCommited().
StringList HttpHeader::headersList [private]
a String vector that contains all HTTP Headers as string
Referenced by addHeader(), and commit().
The documentation for this class was generated from the following files:
httpheader.h
httpheader.cpp