cgixx: Session Class Reference
Session Class Reference
#include <session.h>
Public Member Functions
Session (Request &req)
Session (Request &req, const string &)
void setRequestHandle (Request &)
void start ()
void commit ()
const string & getSessPath () const
void setSessPath (const string &path)
bool add (const string &, const Var &)
stores all sessions
bool exists (const string &)
bool remove (const string &)
bool modify (const string &, const Var &)
const Var get (const string &) const
bool sessionIdProvided () const
Var getSessionId () const
bool set (const string &key, const Var &val)
Public Attributes
sessionCookieParams cookieParams
Holds the session File Name.
ParamsMap item
stores all cookie parameters with which the session ID cookie will be sent
Private Member Functions
string createEmptySessionFile () const
string fullSessionPath (const string &sessId) const
ParamsMap readSessionData () const
void dumpSessionData ()
Private Attributes
Request & requestRef
string sessPath
a reference to global request object
string id
Path to the directory where all session file(s) are going to be stored.
string name
Holds the session ID.
string sessFileName
name of the Session variable
Detailed Description
Global Session Classes which should be accessed through the request Object. stores all sessions as ParamsMap in item member variable holds a reference to global request object
Author:
Neel Basu <neel>
Member Function Documentation
void Session::setRequestHandle (Request & req)
set the reference to global request object to requestRef
void Session::start ()
start's the session.
References createEmptySessionFile(), item, name, readSessionData(), sessFileName, Request::setCookie(), and Var::toString().
Referenced by CGIApp::start().
void Session::commit ()
Commit's the session.
References dumpSessionData().
Referenced by CGIApp::stop().
string Session::createEmptySessionFile () const [private]
create's an empty session file. returns the session ID of the newly created Session file. Session::start()
Referenced by start().
ParamsMap Session::readSessionData () const [private]
Read's session Data from the session File and returns it into ParamsMap format
References sessFileName.
Referenced by start().
void Session::dumpSessionData () [private]
dump's session data in ParamsMap format into item member variable from the provided session file.
References item, and sessFileName.
Referenced by commit().
bool Session::add (const string & key, const Var & val)
stores all sessions
Add's a session as string, Var key pair into item member variable
References item.
bool Session::exists (const string & key)
checks wheather a session with the provided key exists or not
References item.
Referenced by modify().
bool Session::remove (const string & key)
removes a session
References item.
bool Session::modify (const string & key, const Var & val)
modifies a session
References exists(), and item.
const Var Session::get (const string & key) const
get value of a Session
{@
Todo:
for Debug purpouse Only
Todo:
for Debug purpouse Only
References item.
The documentation for this class was generated from the following files:
session.h
session.cpp