cgixx: Request Class Reference
Request Class Reference
#include <apprequest.h>
Public Member Functions
Request (HttpHeader &headerRefObj)
Path Info from parent Class.
bool isGet ()
bool isPost ()
void setCookie (const string &key, const Var &val, const string &domain="", const string &path="/", const time_t &exp=0x0)
Public Attributes
ParamsMap get
Weekdays in 3character First Caps Case format.
ParamsMap post
Hold's GET request parameters key value pairs.
ParamsMap cookie
POST request parameters key value pairs.
StringList pathInfo
cookie's key value pairs
Static Public Attributes
static const std::string weekDays [7] = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"}
Private Member Functions
ParamsMap __params (const char *rawQuery, char sep='&')
ParamsMap __getParams ()
ParamsMap __postParams ()
ParamsMap __cookieParams ()
Private Attributes
HttpHeader & headerRef
Detailed Description
The Global Request Object. Handles GET/POST/COOKIE Requests Holds a non-const referencs to the global HTTPHeader Object in headerRef private member variable
Author:
Neel Basu <neel>
Constructor & Destructor Documentation
Request::Request (HttpHeader & headerRefObj)
Path Info from parent Class.
Initializes the HTTP Header Object initializes get, post, cookie member variables by invoking __getParams(), __postParams(), and __cookieParams()
References __cookieParams(), __getParams(), __postParams(), cookie, pathInfo, and post.
Member Function Documentation
ParamsMap Request::__getParams () [private]
Read's HTTP Request's GET directive and returns key Value pair's map. Its return value is stored into get member variable
Referenced by Request().
ParamsMap Request::__postParams () [private]
Read's HTTP Request's POST directive and returns key Value pair's map. Its return value is stored into post member variable
Referenced by Request().
ParamsMap Request::__cookieParams () [private]
Read's HTTP Request's COOKIE directive and returns key Value pair's map. Its return value is stored into cookie member variable
Referenced by Request().
void Request::setCookie (const string & key, const Var & val, const string & domain = "", const string & path = "/", const time_t & exp = 0x0)
Set a Cookie. Created the cookie string and appends it to the cookie ParamsMap member variable
References HttpHeader::addHeader(), and headerRef.
Referenced by Session::start().
Member Data Documentation
HttpHeader& Request::headerRef [private]
a reference to global HTTP header Object initialized by Constructor.
Referenced by setCookie().
The documentation for this class was generated from the following files:
apprequest.h
apprequest.cpp