cgixx: CGIApp Class Reference
CGIApp Class Reference
#include <cgiapp.h>
Public Types
typedef void(CGIApp::* callback)(void)
Public Member Functions
int getSegmentCount () const
void setRoute (const string &urlpath, callback fn)
bool routeExists (const string &urlPath) const
bool removeRoute (const string &urlPath)
Var segment (unsigned int n, bool concat=false, bool fromRoot=false) const
CGIApp (CGILayout *l)
void start ()
virtual void init ()
virtual void subMain ()=0
virtual void destroy ()
void stop ()
int exec ()
void setLayout (CGILayout *l)
Public Attributes
Session session
Request request
HttpHeader header
auto_ptr< CGILayout > layout
Protected Attributes
stringstream res
Private Types
typedef map< std::string,
callback > callbackMap
Private Member Functions
bool callRoute (const string &urlPath)
string detectRoute () const
Private Attributes
string mSegment
int segmentCount
callbackMap clbk
Detailed Description
Author:
Neel Basu <neel>
Member Function Documentation
string CGIApp::detectRoute () const [private]
Reads the url entered by the user and returns appropiate segment key which is callbck map's key.
References getSegmentCount(), routeExists(), segment(), and Var::toString().
Referenced by exec().
int CGIApp::getSegmentCount () const
returns the total number of segments.
Referenced by detectRoute().
bool CGIApp::routeExists (const string & urlPath) const
Todo:
testing
Referenced by detectRoute().
Var CGIApp::segment (unsigned int n, bool concat = false, bool fromRoot = false) const
returns an url segment. e.g. if my url is http://localhost/bin/myapp.bin/x/y/z/m/n/o/p the following code will produce.
        for(int j=0;j<getSegmentCount()+1;j++){
                res<<j<<" | "<<segment(j)<<" | "<<segment(j, true)<<" | "<<segment(j, true, true)<<" | "<<segment(j, false, true)<<endl<<"<br />";
        }
the following Output
                0 | z | /z | /x/y/z | /x/y/z
                1 | m | /z/m | /x/y/z/m | /x/y/z/m
                2 | n | /z/m/n | /x/y/z/m/n | /x/y/z/m/n
                3 | o | /z/m/n/o | /x/y/z/m/n/o | /x/y/z/m/n/o
                4 | p | /z/m/n/o/p | /x/y/z/m/n/o/p | /x/y/z/m/n/o/p
                5 |   | /z/m/n/o/p | /x/y/z/m/n/o/p | /x/y/z/m/n/o/p
                6 |   | /z/m/n/o/p | /x/y/z/m/n/o/p | /x/y/z/m/n/o/p
                7 |   | /z/m/n/o/p | /x/y/z/m/n/o/p | /x/y/z/m/n/o/p
Attention:
when you use segment(j, false, true) its automatically converted to segment(j, true, true) cause segment(j, false, true) has no sense
References Request::pathInfo.
Referenced by detectRoute().
void CGIApp::start ()
start method. System's own initialization method.You can't override start() method. it will get automatically called to initialize CGIApp System. e.g. make request, header, session member variable(s).
References HttpHeader::addHeader(), and Session::start().
Referenced by exec().
void CGIApp::init () [virtual]
Option Initialization method. If you have this method on your own sub Class init method of that one will be invoked. The default init() method provided by base class CGIApp::init() does nothing.
Referenced by exec().
void CGIApp::destroy () [virtual]
Optional onDestroy Method. If you have a destroy() method on your own sub class that method will be invoked. the default destroy() method CGIApp::destroy() does nothing.
Referenced by exec().
void CGIApp::stop ()
stop method. System's own stop method.You can't override stop() method. it will get automatically called to when your subMain() finishes. it Commits all session Data.
References Session::commit().
Referenced by exec().
int CGIApp::exec ()
meant to be called from Main.
        class myApp: public CGIApp{
                public:
                        void subMain();
        }
        ......
        int main(int argc, char** argv){
                myApp app(argc, argv);
                return app.exec();
        }
References HttpHeader::commit(), destroy(), detectRoute(), init(), HttpHeader::isCommited(), start(), and stop().
The documentation for this class was generated from the following files:
cgiapp.h
cgiapp.cpp